# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demorpcservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demorpcservice.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x64\x65morpcservice.proto\"@\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\r\">\n\x10\x43reatePersonArgs\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\r\"\x1c\n\x0eReadPersonArgs\x12\n\n\x02id\x18\x01 \x01(\t2h\n\x0e\x44\x65moRPCService\x12,\n\x0c\x43reatePerson\x12\x11.CreatePersonArgs\x1a\x07.Person\"\x00\x12(\n\nReadPerson\x12\x0f.ReadPersonArgs\x1a\x07.Person\"\x00\x42\x06Z\x04mainb\x06proto3')
)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Person.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Person.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surname', full_name='Person.surname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='Person.age', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=88,
)


_CREATEPERSONARGS = _descriptor.Descriptor(
  name='CreatePersonArgs',
  full_name='CreatePersonArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreatePersonArgs.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surname', full_name='CreatePersonArgs.surname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='CreatePersonArgs.age', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=152,
)


_READPERSONARGS = _descriptor.Descriptor(
  name='ReadPersonArgs',
  full_name='ReadPersonArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReadPersonArgs.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=182,
)

DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['CreatePersonArgs'] = _CREATEPERSONARGS
DESCRIPTOR.message_types_by_name['ReadPersonArgs'] = _READPERSONARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'demorpcservice_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  ))
_sym_db.RegisterMessage(Person)

CreatePersonArgs = _reflection.GeneratedProtocolMessageType('CreatePersonArgs', (_message.Message,), dict(
  DESCRIPTOR = _CREATEPERSONARGS,
  __module__ = 'demorpcservice_pb2'
  # @@protoc_insertion_point(class_scope:CreatePersonArgs)
  ))
_sym_db.RegisterMessage(CreatePersonArgs)

ReadPersonArgs = _reflection.GeneratedProtocolMessageType('ReadPersonArgs', (_message.Message,), dict(
  DESCRIPTOR = _READPERSONARGS,
  __module__ = 'demorpcservice_pb2'
  # @@protoc_insertion_point(class_scope:ReadPersonArgs)
  ))
_sym_db.RegisterMessage(ReadPersonArgs)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\004main'))

_DEMORPCSERVICE = _descriptor.ServiceDescriptor(
  name='DemoRPCService',
  full_name='DemoRPCService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=184,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreatePerson',
    full_name='DemoRPCService.CreatePerson',
    index=0,
    containing_service=None,
    input_type=_CREATEPERSONARGS,
    output_type=_PERSON,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadPerson',
    full_name='DemoRPCService.ReadPerson',
    index=1,
    containing_service=None,
    input_type=_READPERSONARGS,
    output_type=_PERSON,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMORPCSERVICE)

DESCRIPTOR.services_by_name['DemoRPCService'] = _DEMORPCSERVICE

# @@protoc_insertion_point(module_scope)
