// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demorpcservice.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Person object represents a human.
type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Age                  uint32   `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_demorpcservice_0a806e1e83d782b7, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Person) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type CreatePersonArgs struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePersonArgs) Reset()         { *m = CreatePersonArgs{} }
func (m *CreatePersonArgs) String() string { return proto.CompactTextString(m) }
func (*CreatePersonArgs) ProtoMessage()    {}
func (*CreatePersonArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_demorpcservice_0a806e1e83d782b7, []int{1}
}
func (m *CreatePersonArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonArgs.Unmarshal(m, b)
}
func (m *CreatePersonArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonArgs.Marshal(b, m, deterministic)
}
func (dst *CreatePersonArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonArgs.Merge(dst, src)
}
func (m *CreatePersonArgs) XXX_Size() int {
	return xxx_messageInfo_CreatePersonArgs.Size(m)
}
func (m *CreatePersonArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonArgs proto.InternalMessageInfo

func (m *CreatePersonArgs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePersonArgs) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *CreatePersonArgs) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type ReadPersonArgs struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPersonArgs) Reset()         { *m = ReadPersonArgs{} }
func (m *ReadPersonArgs) String() string { return proto.CompactTextString(m) }
func (*ReadPersonArgs) ProtoMessage()    {}
func (*ReadPersonArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_demorpcservice_0a806e1e83d782b7, []int{2}
}
func (m *ReadPersonArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPersonArgs.Unmarshal(m, b)
}
func (m *ReadPersonArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPersonArgs.Marshal(b, m, deterministic)
}
func (dst *ReadPersonArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPersonArgs.Merge(dst, src)
}
func (m *ReadPersonArgs) XXX_Size() int {
	return xxx_messageInfo_ReadPersonArgs.Size(m)
}
func (m *ReadPersonArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPersonArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPersonArgs proto.InternalMessageInfo

func (m *ReadPersonArgs) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*CreatePersonArgs)(nil), "CreatePersonArgs")
	proto.RegisterType((*ReadPersonArgs)(nil), "ReadPersonArgs")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoRPCServiceClient is the client API for DemoRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoRPCServiceClient interface {
	// Creates a Person
	CreatePerson(ctx context.Context, in *CreatePersonArgs, opts ...grpc.CallOption) (*Person, error)
	// Reads a Person
	ReadPerson(ctx context.Context, in *ReadPersonArgs, opts ...grpc.CallOption) (*Person, error)
}

type demoRPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewDemoRPCServiceClient(cc *grpc.ClientConn) DemoRPCServiceClient {
	return &demoRPCServiceClient{cc}
}

func (c *demoRPCServiceClient) CreatePerson(ctx context.Context, in *CreatePersonArgs, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/DemoRPCService/CreatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoRPCServiceClient) ReadPerson(ctx context.Context, in *ReadPersonArgs, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/DemoRPCService/ReadPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoRPCServiceServer is the server API for DemoRPCService service.
type DemoRPCServiceServer interface {
	// Creates a Person
	CreatePerson(context.Context, *CreatePersonArgs) (*Person, error)
	// Reads a Person
	ReadPerson(context.Context, *ReadPersonArgs) (*Person, error)
}

func RegisterDemoRPCServiceServer(s *grpc.Server, srv DemoRPCServiceServer) {
	s.RegisterService(&_DemoRPCService_serviceDesc, srv)
}

func _DemoRPCService_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoRPCServiceServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DemoRPCService/CreatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoRPCServiceServer).CreatePerson(ctx, req.(*CreatePersonArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoRPCService_ReadPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPersonArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoRPCServiceServer).ReadPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DemoRPCService/ReadPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoRPCServiceServer).ReadPerson(ctx, req.(*ReadPersonArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DemoRPCService",
	HandlerType: (*DemoRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _DemoRPCService_CreatePerson_Handler,
		},
		{
			MethodName: "ReadPerson",
			Handler:    _DemoRPCService_ReadPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demorpcservice.proto",
}

func init() {
	proto.RegisterFile("demorpcservice.proto", fileDescriptor_demorpcservice_0a806e1e83d782b7)
}

var fileDescriptor_demorpcservice_0a806e1e83d782b7 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0x86, 0x30,
	0x14, 0x85, 0x6d, 0x21, 0xfc, 0xf1, 0x46, 0xf1, 0xf7, 0xc6, 0xa1, 0x71, 0x22, 0x4c, 0x0c, 0xa6,
	0x83, 0x3e, 0x81, 0xfe, 0x3e, 0x00, 0xa9, 0x8b, 0x71, 0xab, 0xf4, 0x06, 0x3b, 0x94, 0x92, 0x16,
	0x7d, 0x7e, 0x63, 0x89, 0x82, 0x84, 0xed, 0x9c, 0x93, 0xe6, 0x3b, 0xa7, 0x17, 0x6e, 0x0c, 0x39,
	0x1f, 0xc6, 0x2e, 0x52, 0xf8, 0xb2, 0x1d, 0xc9, 0x31, 0xf8, 0xc9, 0xd7, 0xaf, 0x50, 0xb4, 0x14,
	0xa2, 0x1f, 0xb0, 0x04, 0x6e, 0x8d, 0x60, 0x15, 0x6b, 0xce, 0x15, 0xb7, 0x06, 0x11, 0xf2, 0x41,
	0x3b, 0x12, 0x3c, 0x25, 0x49, 0xa3, 0x80, 0x43, 0xfc, 0x0c, 0x29, 0xce, 0x52, 0xfc, 0x6b, 0xf1,
	0x08, 0x99, 0xee, 0x49, 0xe4, 0x15, 0x6b, 0x2e, 0xd5, 0x8f, 0xac, 0x15, 0x1c, 0x4f, 0x81, 0xf4,
	0x44, 0x33, 0xff, 0x31, 0xf4, 0xf1, 0x8f, 0xc9, 0xf6, 0x99, 0x7c, 0x97, 0x99, 0x2d, 0xcc, 0x0a,
	0x4a, 0x45, 0xda, 0xac, 0x88, 0x9b, 0xd5, 0xf7, 0x1f, 0x50, 0x3e, 0x93, 0xf3, 0xaa, 0x3d, 0xbd,
	0xcc, 0xff, 0xc4, 0x3b, 0xb8, 0x58, 0xef, 0xc0, 0x6b, 0xb9, 0x9d, 0x75, 0x7b, 0x90, 0xb3, 0xa9,
	0xcf, 0xb0, 0x01, 0x58, 0x1a, 0xf0, 0x4a, 0xfe, 0xaf, 0x5b, 0xbd, 0x7c, 0x2a, 0xde, 0x72, 0xa7,
	0xed, 0xf0, 0x5e, 0xa4, 0x43, 0x3e, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x98, 0x3b, 0x3e, 0x0e,
	0x60, 0x01, 0x00, 0x00,
}
